[package]
name = "yacht-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
description.workspace = true
[[bin]]
name = "yacht"
path = "src/main.rs"
[dependencies]
yacht-core = { path = "../yacht-core" }
serde_json.workspace = true
ctrlc = "3.5.2"
